version: 2.1


# -- ORBS --
#orbs:
#  node: circleci/node@x.y


# -- PARAMETERS --
parameters:
  enable-cool-feature:
    type: boolean
    default: True


# -- EXECUTORS --
executors:
  alpine-executor:
    docker:
      - image: cimg/base:stable
  python-executor:
    docker:
      - image: cimg/python:3.8


# -- STEPS --
commands:
  step_install-pip3:
    description: "Install pip3"
    steps:
      - run:
          name: Install pip3
          command: |
            sudo apt update && sudo apt install python3-pip
    

# -- JOBS --
jobs:
  build-super-cool-feature:
    executor: python-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""
      - step_install-pip3

  echo:
    executor: alpine-executor
    steps:
      - run:
          name: Echo
          command: echo "Hello World"

  env-dependent-templateL: &env-dependent-template
    executor: alpine-executor
    steps:
      - run:
          name: Echo
          command: echo "$TEST_VAR"

  dev_env_dependent_job:
    <<: *env-dependent-template
  qa_env_dependent_job:
    <<: *env-dependent-template
  prod_env_dependent_job:
    <<: *env-dependent-template


# -- WORKFLOWS --
workflows:
  version: 2

  build:
    jobs:
      - echo:
          context: dev
      - hold-before-manual-approval:
          type: approval
          requires:
            - echo
      - dev_env_dependent_job:
          context: dev
          requires:
            - hold-before-manual-approval
      - build-super-cool-feature:
          context: dev
          requires:
            - dev_env_dependent_job
